# Generated by Django 4.0.6 on 2024-02-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название элемента под-меню')),
                ('description', models.TextField(max_length=100, verbose_name='Описание элемента под-меню')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.menuitem', verbose_name='Элемент меню')),
            ],
            options={
                'verbose_name': 'Элемент под-меню',
            },
        ),
    ]
