# Generated by Django 4.0.6 on 2024-02-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_submenuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элементы меню'},
        ),
        migrations.AlterModelOptions(
            name='submenuitem',
            options={'verbose_name': 'Элемент под-меню', 'verbose_name_plural': 'Элементы под-меню'},
        ),
    ]
