# Generated by Django 4.0.6 on 2024-02-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_alter_menuitem_options_alter_submenuitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenuitems', to='menuapp.menuitem', verbose_name='Элемент меню'),
        ),
    ]
